version: '3.8'

services:
  db:
    image: postgres
    container_name: quemistry-db
    environment:
      POSTGRES_DB: quemistry
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  question:
    build:
      context: ../question_ms
      dockerfile: Dockerfile
    container_name: question-ms
    depends_on:
      - db
    environment:
      - DB_NAME=quemistry
      - DB_URL=jdbc:postgresql://db:5432/quemistry
      - DB_USER=root
      - DB_PASSWORD=123456
    # ports:
    #   - "81:80"

  user:
    build:
      context: ../user_ms
      dockerfile: Dockerfile
    container_name: user-ms
    depends_on:
      - db
    environment:
      - DATABASE_NAME=quemistry
      - DATABASE_URL=jdbc:postgresql://db:5432/quemistry
      - DATABASE_LOGIN=root
      - DATABASE_SECRET=123456
      - DATABASE_CIPHER_KEY=VT9lVmT791GeD3OXyxZv3vsbZ3fBUtrS
      - DATABASE_CIPHER_KEY_SIZE=1024
      - DATABASE_CIPHER_IV=3b2e1a1e9c1b4b3a
      - HOST_NAME=http://localhost:3000
    # ports:
    #   - "82:80"

  quiz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-ms
    depends_on:
      - db
      - question
    environment:
      - DB_NAME=quemistry
      - DB_URL=jdbc:postgresql://db:5432/quemistry
      - DB_USER=root
      - DB_PASSWORD=123456
      - QUESTION_SERVICE_URL=http://question
      - USER_SERVICE_URL=http://user
    ports:
      - "80:80"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /swagger/statistics_ms-health-openapi.yaml
      URLS: '[{"url":"./statistics_ms-health-openapi.yaml","name":"Health API"},
        {"url":"./statistics_ms-quiz-openapi.yaml","name":"Quiz API"},
        {"url":"./statistics_ms-test-openapi.yaml","name":"Test API"}]'
      statistics_ms_HOST: localhost
    volumes:
      - ./api:/swagger
    ports:
      - "8081:8080"

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"

# volumes:
#  postgres_data:
