spring:
  application:
    name: statistics_ms

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    schemas: qms_report
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /v1
      path-mapping:
        health: /stats/actuator
  endpoint:
    health:
      show-details: never
      enabled: true
  health:
    mail:
      enabled: false

server:
  port: 80

logging:
  level:
    javax.net.ssl: DEBUG